#!/bin/bash

# This bash script uses the current working directory to create a simple
# script to run the TiddlyServer command anywhere in a user's
# workspace.

installScript() {
  scriptName=$1
  cmdScript=$(pwd)/.venv/bin/$scriptName

  cat << CMD_SCRIPT > $HOME/.local/bin/$scriptName
#!/bin/sh

# This shell script was created by the lpilGerbyBuilder tool
#       './scripts/installEditableTiddlyServerCommand'
# script.

exec $cmdScript \$@
CMD_SCRIPT

  chmod a+x $HOME/.local/bin/$scriptName
}

##########################################################################

installScript tiddlyserver
installScript tiddlypacker
installScript tiddlyunpacker
installScript make-tiddlywiki-reenable-plugin-downloads-plugin


echo ""
echo "The editable TiddlyServer commands haver been created"
echo ""
